helium/router

src/router_xor_filter_worker.erl

xor cli was blowing up because of the wrapped response. The spec says
there's no ok, so let's go with that.

Don't wrap return in {ok} tuple

---

src/device/router_device_routing.erl
src/device/router_device_worker.erl
src/lora/lorawan_location.erl

- Hotspots are planing on reporting their subregion as part of AS923, if
they provide, we should respect that.
- Move maybe fetching locations back to every offer. If router is
redeployed and a device does not try to join again, we won't know what
region it's in.

Keep router from falling on its face when hotspots report region_subregion for as923

---

src/lora/lorawan_mac_region.erl

```
exception exit: {{function_clause,[{lorawan_mac_region,f2uch,[926.3,{9152,2},{9159,16}],[{file,"/opt/router/src/lora/lorawan_mac_region.erl"},{line,289}]},{router_utils,format_hotspot,6,[{file,"/opt/router/src/router_utils.erl"},{line,80}]},{router_device_utils,report_join_accept,4,[{file,"/opt/router/src/device/router_device_utils.erl"},{line,487}]},{router_device_worker,handle_info,2,[{file,"/opt/router/src/device/router_device_worker.erl"},{line,584}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},[{gen_event,terminate_server,4,[{file,"gen_event.erl"},{line,354}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]} …
```

Fix rx2_window for AU915

---

src/device/router_device_routing.erl
src/router_utils.erl

This is to improve device log tracing by providing device id when possible to avoid having duplicate messages from other device sharing same `devaddr`

Improve trace logging

---

src/cli/router_cli_device_worker.erl

It's easier to add `--stop` when going through command history than to
get your cursor back before the `--id` of the device you're stopping.
Eventually I'd like to add a listing of current traces, and stopping them from index. But this was an easy quick change to make now.

add flag for stopping device trace

---

src/lora/lorawan_location.erl

Even still, the tests for this pass locally. You can look at the url
being requested and notice that it's all weirdly escaped. Locally,
hackney can handle it, and everything goes through swimmingly. On a
server however (prod in this case) it doesn't like the url and returns
an `{error, nxdomain}` tuple.
This may have been covering up another bug where we were matching
country codes out of ETS incorrectly. I'm still not sure why that test
wasn't failing during CI, as it failed almost immediately where I ran it locally.

fix fetching hotspot locations returning nxdomain

---

src/channels/router_http_channel.erl
test/router_channel_http_SUITE.erl

- add a test for making sure url_params get absorbed
- quick note that headers don't need to be treated like a jsx_map
because we always default to sending content-type if nothing is
provided. Headers should never be empty in the request, even if it's
empty in the channel args.

Accept url_params in channel updates

---

config/sys.config
config/sys.config.src
src/router_sc_worker.erl

- If state channels are failing to open we want to be able to see that
information without asking.
- While scs are being worked on, it might be nice to give them their own
log file.

Up sc_open_failure to warning from debug

---

src/device/router_device.erl
src/lora/lorawan_mac_region.erl
test/router_device_worker_SUITE.erl

We track the uplink datarates for devices. We were not using the mapped
datarate for downlinks when seeing if a payload can be queued. Uplinks
are tighter on size than downlinks are in most cases.

Fix datarate used when queueing downlinks

---

src/device/router_device_worker.erl
test/router_console_api_SUITE.erl

We're attempting to simplify the interactions with queuing downlinks
through console. Queuing through an endpoint or payload_raw we assume
the user is giving us a base64 encoded payload, router decodes and
stores, then sends that to Console (when queue updates are active).
Queueing downlinks through Console are base64 as well, sometimes.
To simplify we're building the contract that router will send whatever
it received back to Console, no need to think about who encoded or
decoded when or where.
Let me know if there's something I've missed thinking about. I have a nag there might be, but can't pinpoint it.

Always send base64 payloads for queue updates

---

.github/workflows/erlang.yml

Address sanitizer seems to not play well with `rustc` itself. I'd prefer to leave ASan enabled, but we run all our c NIFs' tests with it enabled, so we still have a little protection.

Fix broken CI

---

src/device/router_device_devaddr.erl
src/device/router_device_routing.erl

The Type tells you how many bits to read for the netid, but it also
tells you what to prefix the 24bit NetID with to get the resulting NetID.

Fix NetID parsing

---

README.md

Mostly pulled form `lorawan_mac_region.erl`. Some regions freqs come
from `router_device_worker:craft_join_reply/4`. Others are a bit
inferred. We have some built in support because of where we based our
implementation from, other's are more explicit.

Regions and frequencies supported

---

include/router_device_worker.hrl
src/device/router_device_worker.erl
src/lora/lorawan_mac_region.erl
test/router_SUITE.erl
test/router_lorawan_SUITE.erl
test/test_utils.erl

newer lora spec supports an optional channel mask in the cflist for
us915 devices. older specs say devices should ignore non-empty cflists,
but real world testing proved this to be a lie.
We are going to alternate filling the cflist with channel mask
information to give each device a chance to join without having to
register what version devices they are in console. They will still get
channel mask updates in the first packet after a successful join. This
will allow newer devices to be a little smarter.
Count join attempts in device worker. Allows for the alternating
cflists, also something we can potentially look at to see who's having
trouble joining.

Move crafting reply closer to sending join

---

src/device/router_device_worker.erl
src/lora/lorawan_mac_region.erl
test/router_lorawan_SUITE.erl

Closer match the guidelines in the country.
There's a small frequency range where they're allowed full power.
Otherwise default to 14.

Update EU868 donwlink strength

---

rebar.lock

Fixes a bug where grpcbox_socket goes down and cannot restart as another process ( acceptor_pool ) is controlling the listen port.  Ends up breaching supervisor restart strategy, resulting in there being no bound listen port.
Further context is provided in the commit here:
https://github.com/andymck/grpcbox/commit/5698251e2ea80b876fabf85dcee23056b4d02a52#diff-bd51ba329d9c5920edf2350ba05e38bcee9b09c0f866044086fea92882950e8eR39

bump grpcbox to pull in grpcbox_socket restart fix

---

.env-template
config/sys.config
config/sys.config.src
src/router_sc_worker.erl

While putting this on a server I'd like to lower the current expiration interval so if things start to run away, its in a more recoverable way.
Router attempts to always have at least 1 safety valve state channel
open. That paired with the expiration calculation lets us get in a
position where we have more than one state channel that closes within a
few blocks of each other.
It appears this is causing latency spikes when multiple channels are
closed close together. This is an attempt to have some minimum amount of
time between closes to prevent bursts of packets that have been waiting
to get into a state channel.
note: exhausted state channels can not close, they have to wait for
their expiry time.
It might be a good idea to brainstorm a different way to think about
state channel …

Add buffer calc to sc expiration

---

rebar.lock

Silences the invalid_preface error when a non http2 client hits the grpc port 8080. 
Chatterbox commit: https://github.com/andymck/chatterbox/commit/b56a2a08b8a31b7ab0d536e5e8a55d5abe70390f
This is already deployed on various validators.

bump chatterbox, pull in fix to silence invalid preface errors msgs

---

src/device/router_device_channels_worker.erl
src/lora/lorawan_mac_region.erl
src/router_utils.erl

When asking for a channel we assume all frequencies in events going to
console are uplink frequencies. Most of the  time this is okay because
uplinks and downlinks follow more or less the same line. That's not the
case for all regions.
If we can't get a channel assuming an uplink frequency, try assuming
it's a downlink frequency, otherwise we have a good failure on our
hands.
fixes #379

Potential crash when sending events to console

---

src/device/router_device_routing.erl
src/device/router_device_worker.erl
test/router_device_routing_SUITE.erl

When a first packet comes through, a device will cache itself to the
hash for a second. This should help subsequent packets come through
being purchased using the correct devices information.
Devices will re-up the cache for every packet they see, eviction time
automatically happens after 1 second.
multi-buy work tries to wait until the first packet has crossed the line before deciding to buy more.
https://github.com/helium/router/blob/master/src/device/router_device_routing.erl#L204-L206

cache device for packet hash at first sight

---

rebar.lock

Pulls in fixes for two grpc related issues
1.  Fix for when the grpcbox_socket goes down and cannot restart as another process ( acceptor_pool ) is controlling the listen port.  Ends up breaching supervisor restart strategy, resulting in there being no bound listen port.   Grpcbox is effectively down.
https://github.com/andymck/grpcbox/commit/5698251e2ea80b876fabf85dcee23056b4d02a52
https://github.com/andymck/grpcbox/commit/b92d38b208fa2ffcdd5c654362252f43f5d313d7
2.  Fix for when a client connecting over a streaming channel, the server would not return the grpc headers until the first data msgs was returned.  This presents a problem for some clients ( such as our rust client ) which expects the grpc headers to be returned within 10 secs and if not will give up and reset.  This fix …

bump grpcbox, fix grpc reconnect issue and pool not restarting

---

.env-template
config/sys.config.src
src/device/router_device_devaddr.erl
src/device/router_device_worker.erl
test/router_device_devaddr_SUITE.erl
test/router_device_routing_SUITE.erl
test/router_lorawan_SUITE.erl
test/test_utils.erl

The scenario where we potentially return an error and fallback to
default_devaddr was removed quite a while ago, and having the default
devaddr in settings causes confusion.
re: https://github.com/helium/router/issues/413

remove default devaddr

---

src/device/router_device_worker.erl
test/router_SUITE.erl

When channel correction is to be part of a downlink, our frame timeout
needs to be the short window so we have a chance of getting the downlink
to the device within the RX window.
It would be nicer to ask the frame if there are any FOpts going down,
but we don't know that when we're calculating the timeout. It could be
moved to before hand, but that will take some different work.

Consider channel_correction in calculating frame timeout

---

src/apis/router_console_api.erl
src/apis/router_console_ws_worker.erl
src/router_db.erl
test/router_SUITE.erl
test/router_channel_aws_SUITE.erl
test/router_channel_console_SUITE.erl
test/router_channel_http_SUITE.erl
test/router_channel_mqtt_SUITE.erl
test/router_channel_no_channel_SUITE.erl
test/router_console_api_SUITE.erl
test/router_console_dc_tracker_SUITE.erl
test/router_data_SUITE.erl
test/router_decoder_SUITE.erl
test/router_device_channels_worker_SUITE.erl
test/router_device_devaddr_SUITE.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl
test/router_downlink_SUITE.erl
test/router_lorawan_SUITE.erl

If a device becomes unlinked from from an org somehow and router does
not catch that, it will continue to pull it from the database when
offers come in with the matching EUI or devaddr. Nothing can really get
rid of the device now because the supervisor didn't _actually_ start
anything, so there's nothing to kill, and we don't have any db sweeps to
clean out old devices.

Remove devices that don't exist when posting events

---

src/decoders/router_decoder_custom_sup.erl

We don't provide error checking while decoder functions are being
written, and sometimes arguments feel like they're being hugged a bit
too much in their arg-list. Let's allow for some breathing room.
Fixes #419

Allow more whitespace around arg-list in decoders

---

src/channels/router_channel.erl
src/device/router_device_worker.erl

These tests will mostly protect from fields that are added to the record.
All fields exist in these records exist because we use them somewhere.
If a field name is changed the compiler will warn us.
If a field is removed, same complaint.

Make sure we fail CI if #downlink{} or #channel{} are changed

---

src/channels/router_channel.erl
test/router_device_channels_worker_SUITE.erl

Join frames don't have payloads, so there's nothing to decode.

Skip Decoders when sending join-req to integration

---

src/apis/router_console_api.erl
src/device/router_device_channels_worker.erl

Fix for issue #484
If the API is having issue we do not try refetch channels and just return an empty list. We now, will retry to get channels (integrations) if the first API call failed to ensure proper channel startup

Retry to get channels if it fails

---

config/test.config
src/decoders/router_decoder_custom_sup.erl
src/decoders/router_decoder_custom_worker.erl
test/router_decoder_SUITE.erl
test/router_decoder_custom_sup_SUITE.erl
test/router_decoder_custom_worker_SUITE.erl
test/router_v8_SUITE.erl

When a custom decoder function (written in JavaScript) fails, this PR has router track that it failed and avoids further calls to V8 VM for it.
An Erlang process still gets created, because overall, that leads to less computation at runtime when subsequent frames arrive to be passed through that custom decoder.
(There may be room for improvement.  It may be possible to terminate the Erlang process and test earlier in the work-flow when subsequent frames arrive yet before attempting to message the process.)
This partially addresses the reason why issue  #486 was created.
This fixes issue #495 for multiple causes that lead to why `no_context` was being returned within `decoded` object for custom decoders.

Graceful recovery of worker after javascript errors

---

src/lora/lorawan_mac_region.erl

It looks like the US table is used for EU868 as well. 
Reading
https://lora-developers.semtech.com/documentation/tech-papers-and-guides/the-book/packet-size-considerations
this should be different for EU868.

Add EU868 payload size map

---

src/device/router_device_routing.erl

State Channels were recently made parallel.
I think this would help in cases of unlimited buy. 
Need some more heads to think through what would happen on limited buy, and 1 buy.
Questions:
Is there a chance we can accidentally buy too many packets?

add read/write concurrency to routing ets

---

src/device/router_device_channels_worker.erl
src/router_utils.erl
test/router_device_channels_worker_SUITE.erl

When removing channels because the API has told us they should no longer exist, make sure we remove the backoffs with them.
ref: #458

Remove a channels backoff when it's deleted

---

include/lorawan_db.hrl
src/apis/router_console_api.erl
src/device/router_device_routing.erl
src/device/router_device_worker.erl
src/lora/lorawan_mac_commands.erl
src/lora/lorawan_mac_region.erl
src/lora/lorawan_utils.erl
test/console_callback.erl
test/router_SUITE.erl
test/router_channel_azure_SUITE.erl
test/router_channel_console_SUITE.erl
test/router_channel_http_SUITE.erl
test/router_channel_mqtt_SUITE.erl
test/router_channel_no_channel_SUITE.erl
test/router_console_dc_tracker_SUITE.erl
test/router_data_SUITE.erl
test/router_decoder_SUITE.erl
test/router_device_channels_worker_SUITE.erl
test/router_device_devaddr_SUITE.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl
test/router_discovery_SUITE.erl
test/router_downlink_SUITE.erl
test/router_lorawan_SUITE.erl
test/test_utils.erl

- This should resolve issue #531
- This will assist devices in regions where internet backbone latency contributes to timing issues; e.g., AU->US
- For this feature to be fully function, it is blocked by Console [PR#952](https://github.com/helium/console/pull/952)

Add `rx_delay` from Console to LoRaWAN config

---

src/lora/lorawan_mac_region.erl

Per the LoRaWAN 1.0.4 spec:
> The octet order for all multi-octet fields SHALL be little endian.
The original build_bin function builds a variable length byte array memory structure which is big endian by its nature.  The spec requires little endian for all multi-octet fields.  In the chmask case the chmask is always a u16, which is stored little-endian.
Rename build_bin to build_chmask.  It returns a non_neg_integer.  The original code will see a big-endian value.  Swap bytes and transform to little-endian value.
Update and add additional eunit tests to validate all edge cases.

issue #535 - chmask little endian

---

test/router_lorawan_SUITE.erl

CT test is broken
%%% router_lorawan_SUITE ==> US915.lw_join_test: FAILED
%%% router_lorawan_SUITE ==>
Failure/Error: ?assertEqual([8,9,10,11,12,13,14,15], Mask)
expected: [8,9,10,11,12,13,14,15]
got: [0,1,2,3,4,5,6,7]
line: 572
We changed the mask encoding from big-endian to little-endian.  This would change the mask from 0xF0 to 0x0F.  Thus the CT test should be modified to match 0..7.

fix ct test for #535

---

include/metrics.hrl
src/metrics/router_metrics.erl
test/router_metrics_SUITE.erl

We could do the same thing with supervisor:which_children, but the
acceptor_pool uses a different way to report workers than investigating
the supervision tree.

Add grpc connections count metric

---

src/device/router_device.erl
src/device/router_device_worker.erl
test/router_SUITE.erl

- This is Part 3 of adding `rx_delay` feature, the value of which may be set in [Console](https://github.com/helium/console)
- Part 2 was [PR#557](https://github.com/helium/router/pull/557)
- Part 1 was [PR#548](https://github.com/helium/router/pull/548)
- This set of PRs should fully resolve issue #531

Accommodate change to `rx_delay` from Console without device re-joining

---

src/channels/router_channel_utils.erl

Fixes: #451 
When we come across a list where the first item is a map, we assume the
rest of the list is full of maps and we create a 0-indexed map of that
list.
This allows the renderer to continue looking for a value.
You cannot terminate a template value _on_ a list, and you cannot index
into lists of lists.

Add support for indexing into lists in mustache template

---

src/device/router_device_worker.erl
src/lora/lorawan_rxdelay.erl
test/router_SUITE.erl
test/router_channel_azure_SUITE.erl
test/router_channel_console_SUITE.erl
test/router_channel_mqtt_SUITE.erl
test/router_channel_no_channel_SUITE.erl
test/router_console_dc_tracker_SUITE.erl
test/router_data_SUITE.erl
test/router_decoder_SUITE.erl
test/router_device_channels_worker_SUITE.erl
test/router_device_devaddr_SUITE.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl
test/router_discovery_SUITE.erl
test/router_downlink_SUITE.erl
test/router_lorawan_SUITE.erl

This addresses issue #571.
Flow:
- `handle_join()` invokes the new `lorawan_rxdelay:bootstrap()` which establishes state and baseline Del value
- Existing `device_update()` and `get_device()` call the new `lorawan_rxdelay:maybe_update()`
- Handling of `join_timeout` and `handle_frame_timeout()` call `lorawan_rxdelay:adjust()`
- Only `Metadata` and downlink `FOpts` get modified by this flow
Changes to note while reviewing this PR:
- This introduces new states pertaining to `rx_delay`, which supersedes the earlier PR's state key/value pair.
+ *change* was requested via Console/API
+ *requested* device to use new Delay: `FOpts` set for downlink
+ new value has been *established* (ACK from device)
- `rx_delay_ignored_by_device_downlink_test()` has been replaced by: …

Join Accept with non-default rx_delay gets implicit ACK, per LoRaWAN spec

---

Dockerfile

`OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "router": `
We were 1 folder away on the path

Add bin folder to path for access to router exe

---

src/channels/router_channel_utils.erl

This might become a toggle in the future for people who would like to
debug their templates. But for now, we revert to previous working state
of affairs.

Don't throw errors on context misses

---

src/channels/router_azure_connection.erl

HTTP worked fine previously because the URI the token uses as a base
does not contain any special characters.
When connecting to MQTT, however, the URI contains the device-name after
a slash along with the api-version. The slashes are expected to be
url-encoded.
Until we upgrade OTP versions again, we're going to continune the use of
`http_uri:encode/1`.
refs:
`http_uri:encode/1` deprecation has been postponed to OTP/26
https://github.com/erlang/otp/pull/5696
OTP PR implementing `quote/unquote` in `uri_string`.
https://github.com/erlang/otp/pull/5700
OTP Issue no replacement for `http_uri:encode/1` in `uri_string`
https://github.com/erlang/otp/issues/5368

Encode URI when generating SAS token for azure

---

src/channels/router_azure_connection.erl

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly-as-a-device
The host for connecting to the mqtt endpoint is not the same as http,
but the http is technically the resource uri in question.
Here's a point of confusion I can't quite wrap my head around.
When this integration was originally released, everything worked. 
But now we need an entirely different password?

password uri uses the resource uri

---

src/device/router_device_worker.erl
test/console_callback.erl
test/router_device_worker_SUITE.erl
test/test_utils.erl

This keeps router from buying packets for devices that have changed
their join credentials but have not turned off/on the device again to
make a new session.

unset devaddr when console device has app_eui or dev_eui changed

---

src/device/router_device_channels_worker.erl
src/device/router_device_worker.erl
test/router_SUITE.erl
test/router_channel_console_SUITE.erl
test/router_channel_http_SUITE.erl
test/router_channel_iot_hub_SUITE.erl
test/router_channel_mqtt_SUITE.erl
test/router_channel_no_channel_SUITE.erl
test/router_console_dc_tracker_SUITE.erl
test/router_data_SUITE.erl
test/router_decoder_SUITE.erl
test/router_device_channels_worker_SUITE.erl
test/router_device_devaddr_SUITE.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl
test/router_discovery_SUITE.erl
test/router_downlink_SUITE.erl
test/router_lorawan_SUITE.erl
test/router_xor_filter_SUITE.erl

This PR adds DC balance and nonce (integers, both) to channel messages.  The added fields look like this:
```
"dc" : {
"dc_balance": 42,
"nonce": 123456
}
```

Send DC balance to channels (#611)

---

src/device/router_device_worker.erl
src/lora/lorawan_mac_region.erl
test/router_device_worker_SUITE.erl

Solution to address #633.  The spec allows Tx=0xF and Dr=0xF to indicated that DR and/or TX should be ignored and the end-device should continue to use it's current DR and TX settings.

Ignore TxDr Logic

---

src/channels/router_aws_channel.erl

Note: the last certificate seems to be the oldest

Handle case where aws thing has multiple certificates attached

---

src/device/router_device_channels_worker.erl
test/router_SUITE.erl
test/router_channel_console_SUITE.erl
test/router_channel_http_SUITE.erl
test/router_channel_iot_hub_SUITE.erl
test/router_channel_mqtt_SUITE.erl
test/router_channel_no_channel_SUITE.erl
test/router_console_dc_tracker_SUITE.erl
test/router_data_SUITE.erl
test/router_decoder_SUITE.erl
test/router_device_channels_worker_SUITE.erl
test/router_device_devaddr_SUITE.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl
test/router_discovery_SUITE.erl
test/router_downlink_SUITE.erl
test/router_lorawan_SUITE.erl

This commit renames the "dc_balance" field found in channel data to
"balance".

Rename "dc_balance" to "balance"

---

src/cli/router_cli_xor_filter.erl
src/router_utils.erl
src/router_xor_filter_worker.erl
test/router_xor_filter_SUITE.erl

fixes error
```
RPC to 'router@127.0.0.1' failed: {'EXIT',
{function_clause,
[{lists,zip,
[[{1,0},{2,0},{3,0},{4,0}],[]],
[{file,"lists.erl"},{line,391}]},
{lists,zip,2,
[{file,"lists.erl"},{line,391}]},
{router_cli_xor_filter,filter_report,3,
[{file,
"/opt/router/src/cli/router_cli_xor_filter.erl"},
{line,221}]},
{clique_command,run,1,
```

fix xor filter reporting error when not all filters are in use

---

src/cli/router_cli_xor_filter.erl

Up to now we've been lucky in that the flag name has always matched the
longname.
{flag key, {shortname, "matches as string"}, {longname, "secondary match as string"}}

provide short name in string for contains command

---

src/cli/router_cli_device_worker.erl

Time to learn the lesson of erlang's global term ordering, and why we
need to make sure to use guards.

order undefined value before matching on comparable number

---

.env-template
Makefile
config/sys.config.src
include/metrics.hrl
include/router_device.hrl
src/cli/router_cli_hotspot_rep.erl
src/device/router_device.erl
src/device/router_device_cache.erl
src/device/router_device_devaddr.erl
src/device/router_device_routing.erl
src/device/router_device_stats.erl
src/device/router_device_worker.erl
src/metrics/router_metrics.erl
src/metrics/router_metrics_reporter.erl
src/router_hotspot_reputation.erl
src/router_sup.erl
src/router_utils.erl
test/router_device_worker_SUITE.erl
test/router_lorawan_handler_test.erl
test/test_utils.erl

This PR includes 
- Update reputation system to include `UnknownDevice` delivered packets.
- Make `devaddr` field a list (`devaddrs`) in `router_device` record so that Router can track  multiple devaddrs. until device actually send first `uplink`

Fix join devaddr bug 

---

src/apis/router_console_api.erl
test/console_callback.erl

This PR corrects a defect in the implementation of preferred hotspots:  the list of preferred hotspots received from Console is now decoded from b58 instead of hex.

Use b58 strings in preferred hotspots

---

src/apis/router_console_api.erl
test/console_callback.erl

This PR adds logic to `router_console_api` to decode preferred hotspots as a list of binaries containing b58 strings.

Expect preferred hotspots as binary b58 strings

---

rebar.lock

includes fix for floating point frequency causing bad downlink channels

ugprade erlang_lorawan - 8e4866

---

src/apis/router_console_dc_tracker.erl
src/apis/router_console_sup.erl
src/router_sup.erl

Something can take down the dc tracker table, and it will just stay down. preventing us from purchasing any packets.

move ets init to supervisor

---

rebar.lock

https://github.com/helium/erlang-lorawan/pull/8
The erlang-lorawan library causes issues with Downlinks.
One core issue: there was a typo in the list of DataRates. Somehow I missed adding the SF7BW500 datarate. That list determines the up to down datarate on the Downlink RX1 Window.
The added erlang-lorawan unit tests catch the issue. The tests call both the legacy API and the new library API and do a direct output comparison.

update erlang-lorawan library

---

rebar.lock
test/router_data_SUITE.erl

Erlang-LoRaWAN library PR - https://github.com/helium/erlang-lorawan/pull/9
1. CN470 - Corrected channel listen frequencies.
2. Round to Nearest - Changed the frequency float rounding algorithm to a nearest match algorithm. CN470, EU433 and IN865 use multi decimal point frequencies which break a simple rounding function. An easier and elegant approach is to search the entire list of expected frequencies and find the closest match. This works generically for all plans. For example, 865.0625 is an IN865 Uplink channel. In this case 865.061 should adjust to 8065.0625 and not 865.1
3. Fat Channels - US915 and AU915 support fat Uplink channels which operate within a 250 or 500 kHz band. Added the fat channels to the Plan Uplink list. Most code should handle the higher data rate seamlessly.
4. …

Erlang-LoRaWAN library improvements

---

.env-template
config/sys.config
config/sys.config.src
config/test.config
src/metrics/router_metrics.erl

Fix for https://github.com/helium/router/issues/679

Allow to change port for metrics scraper

---

src/device/router_device_worker.erl
src/lora/lorawan_mac_commands.erl
test/router_device_worker_SUITE.erl

Fixes https://github.com/helium/router/issues/724
Simpler implementation of make_link_adr_req which internally handles the Region logic.  One simplification is that all datarate formats are automatically handled.  Second, we determine the downlink datarate based on the incoming datarate which fixes the issue with #724
build_link_adr_req was created via this PR - https://github.com/helium/erlang-lorawan/pull/9

use build_link_addr_req

---

config/sys.config
config/sys.config.src
config/testnet.config.src
src/router_utils.erl

Related PR: https://github.com/helium/sibyl/pull/66
This adds support for routers to gossip their grpc address and fixes an issue whereby gateway-rs clients were being returned invalid grpc ports for router data from durable validators.  
With this fix, routers will gossip the grpc address ( including public ip and port ) to its peers.  Validators will then be able to derive this data from the peerbook and use it to return router routing addresses to clients.

add support for gossipping a grpc address

---

src/apis/router_console_api.erl
test/router_SUITE.erl
test/router_data_SUITE.erl
test/router_downlink_SUITE.erl
test/router_lorawan_SUITE.erl

This PR addresses issue #757.  It corrects a bug where Router sent an incorrectly formatted event message to Console when the subcategory was `downlink_ack`. Specifically, the `integration` and `mac` keys were omitted.

Send a properly formed downlink_ack event to Console

---

rebar.lock
src/device/router_device_worker.erl

Add lager debug to better log and understand why AU915 sub-bank 5 connections fall through with AS923-1 hotspots.

update library and add lager debug

---

src/device/router_device_routing.erl
src/grpc/helium_router_service.erl
test/router_grpc_SUITE.erl

- send back the error atom when not handling an packet
- explicitly call out timeouts
NOTE: We respond to packets that don't require a downlink with
`#{accepted => true}` after the frame timeout has elapsed.

More responses to grpc endpoints

---

src/device/router_device.erl
src/device/router_device_routing.erl
src/device/router_device_worker.erl
test/router_data_SUITE.erl

DualPlan is a feature we wish to deploy ASAP.  It allows both AS923-1 and AU915 end-devices to Join the same Gateway.  This is achieved with the DualPlan feature code which was already implemented.  During AU915 testing some issues were discovered.
Currently the Join Response frequency mirrors the Join Uplink frequency.  This indicates we are still using the Hotspot Region rather than the DeviceRegion to determine the Downlink channel.
Discovered the issue during debugging on Dev.  We cache the device Region during the Join.  This device cache was not always being used, rather the HotspotRegion was used instead.  The solution is to handle any cases where the device Region should be used, rather than the HotspotRegion.
Solution tested on Dev with an AS923-1 Hotspot while connecting with an …

dual plan region fix

---

docs/runbook.md

This only touches the `docs/` subdirectory to update the runbook.
For when on-call, please proofread with perspective of being sleepy at 3AM.
- True story based upon recent events
- Names and locations have been changed to protect the innocent

Expand instructions for Load Snapshot

---

rebar.config
rebar.lock

Sync with proto PR.  Fixes compile issue because 25fc8c no longer exists.
https://github.com/helium/proto/pull/193

update proto ref

---

rebar.lock
test/router_data_SUITE.erl

The chmask code in the LoRaWAN library requires knowledge of the specific region, e.g. AS923_1B or AU915_SB5.  Without knowing the specific Region names, the library has default behavior.
This update is intended to fix issues found by sensor users in Malaysia and Australia.

update lorawan library

---

config/sys.config.src
src/device/router_device_devaddr.erl
src/grpc/router_ics_devaddr_worker.erl
src/grpc/router_ics_eui_worker.erl
src/grpc/router_ics_gateway_location_worker.erl
src/grpc/router_ics_route_get_devaddrs_handler.erl
src/grpc/router_ics_route_get_euis_handler.erl
src/grpc/router_ics_skf_worker.erl
src/router_sup.erl
src/router_utils.erl
test/router_device_devaddr_SUITE.erl
test/router_ics_devaddr_worker_SUITE.erl
test/router_ics_eui_worker_SUITE.erl
test/router_test_ics_route_service.erl
test/test_utils.erl

fetch assignable devaddr range from config service

---

src/cli/router_cli_registry.erl
src/grpc/router_ics_devaddr_worker.erl
src/grpc/router_ics_eui_worker.erl
src/router_sup.erl
src/router_xor_filter_worker.erl
test/router_ics_eui_worker_SUITE.erl
test/router_xor_filter_SUITE.erl

- Require `route_id` for Devaddr and EUI workers to start.
- Disable xor filter worker when EUI worker is enabled.
- Remove xor filter cli when chain is dead.

eui vs xor

---

src/grpc/router_ics_eui_worker.erl
src/grpc/router_ics_skf_worker.erl

they can return {ok, Data}, or just stream_finished.
These tests.
https://github.com/tsloughter/grpcbox/blob/37a7bd8e9abef187c67e9d04f7be967710cc6003/test/grpcbox_SUITE.erl#L373-L392
The way this unary handler accepts `stream_finished` as a success. https://github.com/tsloughter/grpcbox/blob/a5aa6e918a2ddbff40e8ebb3c12b1453fe953e03/src/grpcbox_client.erl#L92-L94
And these `stream_finished` not being wrapped in `{error, _}` tuples. https://github.com/tsloughter/grpcbox/blob/5ea123f2009b26acc6e730801f2b2de17bdfdda2/src/grpcbox_client_stream.erl#L103-L125

Streams can be closed in more than 1 way

---

config/sys.config.src
config/test.config
src/grpc/router_ics_eui_worker.erl
src/grpc/router_ics_skf_worker.erl
test/router_ics_eui_worker_SUITE.erl
test/router_ics_skf_worker_SUITE.erl
test/router_test_ics_route_service.erl
test/router_test_ics_skf_service.erl

Add a retry mechanism when receiving a timeout for a stream close on the eui and skf workers.

ics update timeouts

---

src/device/router_device_worker.erl

This will stop the packet forwarder from throwing away rx2 because it's the same window as rx1 in specific cases.

send undefined for rx2 if what we construct are the same windows

---

config/sys.config.src
config/test.config
src/grpc/router_ics_eui_worker.erl
src/grpc/router_ics_skf_worker.erl
src/grpc/router_ics_utils.erl

If too many items are sent to the config service, it will get stuck reading everything from the network before it will continue doing any db operations, this can be very slow (think minutes). If we added a few strategic pauses to our streaming up of items, the config service can keep up and hopefully not fall behind, making the request seem to take only as long as it takes to send everything up.

add a configurable delay while sending large batches of updates

---

src/device/router_device.erl
src/device/router_device_worker.erl
src/grpc/router_ics_skf_worker.erl
test/router_device_worker_SUITE.erl

We keep the latest 25 DevAddrs and Keys for a device.
If joining takes more than that many attempts, by the time we get a valid first uplink, we may not be able to recreate all the Devaddr,NwkKey pairs that were sent to the config service.
As we roll through the credential limit, we remove pairs that are about to get thrown away.

remove skf from config service as creds are rolled

---

.env-template
config/sys.config.src
config/test.config
src/cli/router_cli_migration.erl
src/device/router_device_devaddr.erl
test/router_device_devaddr_SUITE.erl
test/router_grpc_SUITE.erl
test/router_lorawan_SUITE.erl
test/router_lorawan_handler_test.erl
test/test_utils.erl

:warning: This will __only__ work with Devaddrs of a Type-0 NetID.

expose Devaddr Prefix as env setting

---

src/device/router_device_routing.erl
src/device/router_device_worker.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl

When looking for a device that a packet belongs to, verify the mic with the frame count in the packet rather than the expected frame count from the device.

Search bigger space for packets that belong to devices

---

src/apis/router_console_api.erl
src/apis/router_console_dc_tracker.erl
src/device/router_device_routing.erl
src/device/router_device_worker.erl
test/router_console_dc_tracker_SUITE.erl
test/test_utils.erl

propogate errors from the console api all the way up in the case where a specific org balance cannot be fetched. Avoiding the case where we assume the balance is zero, and the next packet that comes through within the cache time will see that value of zero and force the depletion on Console through another event.

Stop assuming unfetchable orgs balance

---

src/device/router_device_cache.erl

inserting devices into a ets bad where the whole object needs to be unique slows down severely as the table grows but the keys do not grow with the table. Inserting 250k devices spread across 32 devaddrs was approaching 5 minutes.
making a table per devaddr introduces a bit of indirection, but ets sets are fast, and device ids are unique.

ets table per devaddr
