src/lora/lorawan_location.erl

- add a test, request takes a while, so we have a 15s timeout

Create URL binary correctly

---

.env-template

Update p2p seeds in env file

---

src/device/router_device_worker.erl
src/lora/lorawan_mac_region.erl
test/router_lorawan_SUITE.erl

Break out downlink strength per region

---

src/apis/router_console_api.erl

Fix for https://github.com/helium/router/issues/270

Default ADR to false when doing a get_device

---

README.md

Relates to https://github.com/helium/router/issues/268

Update docs to include "unknowng" lat/long

---

src/apis/router_console_api.erl
src/channels/router_channel.erl
src/channels/router_channel_utils.erl
src/channels/router_http_channel.erl
test/router_SUITE.erl
test/router_channel_console_SUITE.erl
test/router_channel_http_SUITE.erl
test/router_channel_no_channel_SUITE.erl
test/router_console_dc_tracker_SUITE.erl
test/router_device_channels_worker_SUITE.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl
test/router_downlink_SUITE.erl
test/router_lorawan_SUITE.erl
test/utils/console_test.hrl
test/utils/test_utils.erl

I'm a little dubious about interpolating the keys of query params. But it's easy enough to rip out, thought I'd add it first to have the discussion.

Enhance http integration with dynamic query parameters

---

src/decoders/router_decoder_custom_sup.erl

- use regex (+1 problem, sorry)
- match arbitrary spacing where allowed in javsacript
- ensure 2 arguments are accepted
Fixes https://github.com/helium/console/issues/560

Accept more valid versions of decoder functions

---

src/router_sc_worker.erl

- Doesn't happen often, but when it does, it can be a pain to track
down the reason.

Forward error for logging when we fail to open a state channel

---

src/decoders/router_decoder_cayenne.erl

Relates to https://github.com/helium/router/issues/289

Add new data to cayenne decoder

---

src/device/router_device_devaddr.erl
src/device/router_device_routing.erl

Update netid parsing

---

src/device/router_device_devaddr.erl
src/device/router_device_routing.erl

- `binary:encode_unsigned/2` converts to the smallest possible representation. We need 32 bits for our parsing to work.
- Return an error tuple when we a devaddr falls ouside the valid net_id_types. (1..7)
- Add tests for values obviously under 32 bits.
- Report invalid_net_id metrics

Fix net_id parsing

---

src/device/router_device_routing.erl

well that can never happen

---

src/device/router_device_worker.erl
test/router_device_worker_SUITE.erl

Offer cache will now clean itself with new offers to avoid weird build ups
Time was also taken down from 10min to 2min

Offer cache auto cleanup

---

src/device/router_device_worker.erl
src/lora/lorawan_mac_region.erl
test/router_SUITE.erl
test/router_lorawan_SUITE.erl

Relevant: https://lora-alliance.org/wp-content/uploads/2021/05/RP-2-1.0.3.pdf

Add CFList to join accept for US915

---

src/router_xor_filter_worker.erl

If there were duplicate devices coming from Console and the filter they
already existed in was chosen for the new updates to go into.
(that filter was the smallest)
The xor hashing would break.
The duplicate eui pairs were being correctly marked as "already in a
filter", but _both_ pairs were marked that way. So when the updates came
through and duplicates were found in the smallest filter, attempting to
construct the new filter would have duplicates in it again.
Solution:
Dedupe the eui pairs we get from console as early as possible.
Duplicates eui pairs are allowed, there's still the app_key to
differentiate devices, and Console has a constraint on the triple
{dev_eui, app_eui, app_key} being unique. We just need to know where to
route joins.

Unique eui pairs coming from console db

---

config/sys.config
config/sys.config.src
src/device/router_device_devaddr.erl

This reverts commit 19fdbba2d2a3676cdc4709c36eed2a1251466b5c.
done testing

Revert "Macpie/force default devaddr (#359)"

---

src/cli/router_cli_dc_tracker.erl

Give more informative message when there are no orgs

---

src/router_sc_worker.erl

Fix for https://github.com/helium/router/issues/407

Use default value when string is empty

---

.env-template
config/sys.config
config/sys.config.src
src/device/router_device.erl
test/router_downlink_SUITE.erl

Add queue size limit to device

---

config/sys.config
config/sys.config.src
src/decoders/router_decoder_custom_worker.erl
src/decoders/router_decoder_sup.erl
src/router_sup.erl

- We are not retrying to decode anymore
- Context creation is done async with some backoff if need be
- v8 and custom decoder sup are now under same sup to avoid taking down more than they should

 Backoff on context creation and add sup

---

src/decoders/router_decoder_custom_worker.erl

temporary fix for crashed contexts invalidating all other contexts

Bring back try mechanism for decoders

---

src/device/router_device_channels_worker.erl
test/router_device_channels_worker_SUITE.erl

Provide hold_time for Join Requests:
- Refers: #468 
- @michaeldjeffrey did the hard work earlier, merged in PR #455
- This merely finishes connecting the feature

Provide hold_time for Join Requests

---

src/router_xor_filter_worker.erl
test/console_callback.erl

To end with, I ran the whole suite 5 times without any failures.
Some tests (xor in particular) rely on being to treat Console endpoints
like a stable store. When we're paginating the results put all the
devices back so we can do it again.

XOR filter test investigation

---

src/cli/router_cli_device_worker.erl

- Add pid if device is running
- Print bin fields in hex

Update device cli output

---

docs/Device.md
docs/Organizations.md
docs/XOR_Filter.md
src/cli/router_cli_device_worker.erl
src/cli/router_cli_organization.erl
src/cli/router_cli_xor_filter.erl

More documentation for https://github.com/helium/router/issues/522 and https://github.com/helium/router/issues/427

update cli docs

---

src/channels/router_http_channel.erl

Add 2s timeout to http integration requests

---

src/cli/router_cli_device_worker.erl

- add device prefix to trace command

support ID flag for device info

---

src/device/router_device_worker.erl
src/lora/lorawan_mac_region.erl

This expands upon PR #531
- Expand rx_window() to use RxDelay

RxDelay Part 2

---

src/device/router_device_routing.erl

Fix for https://github.com/helium/router/issues/537

Fix ets leaks

---

src/device/router_device_routing.erl
test/router_metrics_SUITE.erl

otherwise ets will drop our update on the ground

Replace MB entry with same shape

---

src/device/router_device_routing.erl

`lookup_mb` will return an error when a phash is not found. For denying
more, we only care that it hasn't already been set to the deny_more
configuration.
**Question**: Do we want to loosen the same way for `accept_more`. That would crash if we called accept_more more than once but with different max values.

Loosen deny_more case clause

---

docker-compose-local.yaml
docker-compose.yaml
grafana-dashboard.json
src/device/router_device_routing.erl
src/device/router_device_worker.erl
src/metrics/router_metrics.erl
test/console_test.hrl
test/router_channel_azure_SUITE.erl
test/router_channel_mqtt_SUITE.erl
test/router_lorawan_SUITE.erl

- Add Grafana dashboard for https://github.com/helium/router/issues/596
- Fix for some routing issue 
```** {{case_clause,{ok,<<74,182,34,149,206,8,194,185,241,222,30,158,82,70,55,117,114,186,110,239,185,228,14,106,184,215,247,79,198,199,232,195>>,0,-1}},[{router_device_routing,accept_more,2,[{file,"/opt/router/src/device/router_device_routing.erl"},{line,229}]},{router_device_worker,do_multi_buy,3,[{file,"/opt/router/src/device/router_device_worker.erl"},{line,1344}]},{router_device_worker,validate_frame,9,[{file,"/opt/router/src/device/router_device_worker.erl"},{line,1412}]},{router_device_worker,handle_cast,2,[{file,"/opt/router/src/device/router_device_worker.erl"},{line,700}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,695}]},{gen_server,handle_msg,6,[{file,"gen_server …
```

Various fixes

---

src/device/router_device_worker.erl
src/lora/lorawan_mac_region.erl
test/router_SUITE.erl
test/router_lorawan_SUITE.erl
test/test_utils.erl

Fix for https://github.com/helium/router/issues/556
* Remove alternate cf_list
* cf_list default to true

CfList in US JoinAccept should not alternate

---

src/apis/router_console_api.erl
src/channels/router_iot_hub_channel.erl
src/channels/router_iot_hub_connection.erl
test/console_callback.erl
test/console_test.hrl
test/router_channel_iot_hub_SUITE.erl
test/router_device_channels_worker_SUITE.erl

Helps make space for incoming router_iot_central integration

Rename router_azure_ -> router_iot_hub

---

src/device/router_device_worker.erl
src/router_utils.erl
test/router_SUITE.erl
test/router_downlink_SUITE.erl

Fix for [issues/636](https://github.com/helium/router/issues/636)

Fix fcntdown being off when queueing a downlink manually

---

README.md

Fix for https://github.com/helium/router/issues/646

Add currently supported LoRaWAN versions to Readme.md

---

src/device/router_device.erl

Allow max downlink MTU

---

include/metrics.hrl
src/device/router_device_routing.erl
src/metrics/router_metrics.erl

Help in trying to an idea of how many packets make it into the system
but get dropped for one reason or another because the device can't be
accurately found.

add metric for occurence of unexpected errors in routing

---

.github/workflows/build.yml
.github/workflows/ci_build.yml
Dockerfile
Dockerfile-CI
README.md

Include version into builds

---

src/cli/router_cli_xor_filter.erl

Called as
```sh 
router filter contains --app=XXXXXXXXXXXXXXXX --dev=XXXXXXXXXXXXXXXX
```

Add ability to check all filters for device creds

---

rebar.lock

Some channel frequencies were updated to exactly match frequencies found in Helium's SemTech packet_forwarder configs.
Eunit tests were also updated to better test plan frequencies.

update library erlang-lorawan

---

include/router_device_worker.hrl
src/cli/router_cli_device_worker.erl
src/device/router_device.erl
src/device/router_device_channels_worker.erl
src/device/router_device_worker.erl
src/router_utils.erl
test/router_downlink_SUITE.erl

Add support for region field in queued downlinks sent from the console (https://github.com/helium/console/pull/1141)

Add region field support for downlinks

---

src/metrics/router_metrics.erl

I'm assuming this is a simple typo :)

FIX typo in log output

---

grafana-dashboard.json

FIX another typo

---

src/device/router_device_channels_worker.erl
test/router_device_routing_SUITE.erl

This PR addresses issue #794; it updates the `preferred_hotspots` field of the device metadata sent to Console as as an event.  Preferred hotspot IDs are now properly encoding as B58 strings.

Fix encoding of preferred hotspots in Console events

---

src/channels/router_channel_utils.erl

**context:** https://github.com/helium/router/pull/575
In cases where strings have periods followed by numbers, but none of the
mustache interpolation parts (some encoded string with periods and
numbers) we don't want to think it's an indexed lookup unless there are
brackets present.
We check to make sure the brackets are closed.
If someone using an encoding that allows curly brackets, and somehow
they properly open and close each other, all bets are off, that UB.

Don't replace index lookup when no brackets are present

---

src/device/router_device_worker.erl
test/router_device_worker_SUITE.erl

Fix for https://github.com/helium/router/issues/824

Fix when getting a downlink as an uplink

---

rebar.lock

Lorawan library update to update some of the Datarate up/down tables.
See - https://github.com/helium/erlang-lorawan/commit/29704ae1b29386993bfcf69d1ae4fc04d8502f0e

lorawan update to 29797ae

---

config/sys.config
config/sys.config.src
src/router_utils.erl

ref: https://github.com/helium/miner/pull/1804

pick ability to not gossip with miners from miner repo

---

.github/workflows/tests.yml
Makefile
config/sys.config.src
config/test.config
rebar.config
rebar.lock
src/grpc/helium_gateway_service.erl
src/grpc/helium_packet_service.erl
test/router_grpc_SUITE.erl

update proto service

---

rebar.lock

Revert "update erlang_lorawan ref to 248b59e82"

---

README.md

Update README with correct frequencies for region plans.

update frequencies in readme

---

config/sys.config.src
src/router_blockchain.erl

I have also included the flag `is_chain_dead` to tell if chain was stopped and start using "non chain functions"

Calculate dc_amount locally

---

src/cli/router_cli_migration.erl
src/grpc/router_ics_skf_list_handler.erl
src/grpc/router_ics_skf_worker.erl
test/router_ics_skf_worker_SUITE.erl

- Reconcile upon startup.
- Allow Cli to trigger a reconcile while respecting commit flag.

update skf worker to mirror eui worker

---

rebar.config
rebar.lock
src/apis/router_console_ws_worker.erl
src/grpc/router_ics_skf_worker.erl
test/router_ics_skf_worker_SUITE.erl

https://github.com/helium/proto/pull/300
https://github.com/helium/helium-config-service-cli/pull/40
https://github.com/helium/helium-packet-router/pull/158

send session key filters as hex encoded fields

---

src/device/router_device_routing.erl

When we're handling grpc packets, we know the correct device up front, if we have the device, use it all the way through.
If we don't have the device, do the normal finding of the device for the packet.

thread the found device through handling packet

---

rebar.lock
src/grpc/router_ics_skf_worker.erl

May need this to
https://github.com/helium/erlang-lorawan/pull/28/files

Upgrade lora to  3a18455

---

src/grpc/router_ics_eui_worker.erl
test/router_ics_eui_worker_SUITE.erl

active was only being checked during device updates

check active during reconcile

---

src/grpc/router_ics_skf_worker.erl

Given an add and remove for the same (devaddr,nwkkey) remove the remove, and keep the add.

Dedup incoming updates

---

.env-template
config/sys.config.src
config/test.config
src/apis/router_console_api.erl
src/device/router_device_worker.erl
test/console_callback.erl
test/router_device_worker_SUITE.erl
test/test_utils.erl

Revert "Maybe charge for late packets"

---

src/device/router_device_routing.erl
src/device/router_device_worker.erl
test/router_device_routing_SUITE.erl
test/router_device_worker_SUITE.erl

Revert "Search bigger space for packets that belong to devices"
